coreos/layering-examples

Dockerfile
Use rpm-ostree to install strace. Depends on: https://github.com/coreos/rpm-ostree/pull/3280
=> Dockerfile: use rpm-ostree to install strace

Dockerfile
Fix name of `ostree container commit` command in Dockerfile comment
=> Fix name of `ostree container commit` command

README.md, butane/Dockerfile, butane/demo.bu
We have a lot of useful syntax and semantics in Butane, and it
helps tie our story to Ignition.
(What would be interesting is a tool that "splits" an butane/Ignition
into things like `storage` that need to be firstboot config, and
builds the rest as a container)
=> butane: New example

README.md, wifi/Dockerfile, wifi/ExampleCorpWifi.ini
Support for wireless on FCOS has come up several times, and is
one of the notable differences with current Fedora IoT.  It also
highlights a gap in our support for secret management.
=> wifi: New example

.github/workflows/generate-rhcos-versions.yml, ci/generate-rhcos-versions.py
Does initial generation of the rhcos branch by changing the FROM lines on any Dockerfiles found.
For this to work I think we need:
- create rhcos branch based on the current main branch on this repository.
- to add the https://github.com/coreosbot-releng token to the secrets in this repository.
- fork this repository to github.com/coreosbot-releng/coreos-layering-examples
At least based on my tests with my forks that should make it work. But I don't have the credentials or access to do these things I believe.
=> Add ci to generate examples in rhcos branch

inject-go-binary/Dockerfile
I noticed when working on https://github.com/coreos/coreos-layering-examples
that the rhcos substitution was failing on this one because it
doesn't match `next-devel`.
(Potentially we should fix that *too*, but eh, no reason not to make
things consistent either)
=> inject-go-binary: use FCOS `testing-devel` like everything else

ci/generate-rhcos-versions.py
generate-rhcos-versions: s/file/name/
`file` is a builtin Python keyword, we shouldn't override it.
---
generate-rhcos-versions: De-indent loop
It's more readable this way.
---
generate-rhcos-versions: Only inject `ADD rhel.repo` if needed
Only some of the examples actually install packages, not all.
In particular the `selinux` one does not, and I want to use it
as a test case to fix https://github.com/openshift/os/issues/829
I'm thinking actually we should drop this bit entirely and rely
on host subscriptions *or* users doing it on their own, but
for now this works.
---
=> generate-rhcos-versions: Only inject `ADD rhel.repo` if needed

README.md, replace-systemd/Dockerfile
Minimal example showing replacement of a base core package like systemd
directly from Bodhi.
=> replace-systemd: new example

ansible-firewalld/Dockerfile
ansible-firewalld: Squash into single layer, remove ansible at the end
This ensures we're not actually shipping the ansible code in the
final container, only using it during a build.
---
ansible-firewalld: Add missing cleanups + commit
We need to remember to do this in all of our builds.
---
=> ansible-firewalld: Squash into single layer, remove ansible at the end

.github/workflows/podman-next.yml, podman-next/Containerfile
This will enable podman folks to use that for their custom FCOS builds for podman machine.
=> podman-next: Add example using latest podman from COPR repo

.github/workflows/build-zfs-module.yml, build-zfs-module/Containerfile
Co-authored-by: Micah Abbott
This example builds the rpms for the ZFS module using multi stage builds.
Few fun things learned from this: @ashcrow found out that `ld` is not properly installed on CoreOS/Silverblue it looks like it's the %post script failing. I found out that because the Makefile tries to create a folder using 'mkdir -p /usr/local/X' and `/usr/local` is a link to `/var/usrlocal` it fails. Based on these two constraints building in a intermediate fedora application container(non-ostree) seems like the best way forward at the moment.
Closes #40
=> build-zfs-module: Add example building a kernel module

podman-next/Containerfile
Example fails due to conflicting containers-common-extra versions, this should fix it. 
Signed-off-by: Ashley Cui <acui@redhat.com>
=> podman-next: Add containers-common-extra

replace-kernel/Containerfile, replace-kernel/dracut_call.sh
temporary workaround for https://github.com/coreos/rpm-ostree/issues/4190 while rpm-ostree 2022.18 hits CoreOS stable stream.
=> replace-kernel: rebuild initramfs when rpm-ostree is older than 2022.18

ansible-firewalld/Containerfile, build-zfs-module/Containerfile, podman-next/Containerfile, replace-kernel/Containerfile, replace-systemd/Containerfile, rsyslog/Containerfile, tailscale/Containerfile, wifi/Containerfile
Supersedes https://github.com/coreos/layering-examples/pull/33
This command just deletes content from /var/cache, but that's no longer needed since it's part of
https://github.com/ostreedev/ostree-rs-ext/pull/367
=> tree-wide: Drop rpm-ostree cleanup -m

replace-systemd/Containerfile
This works around: https://github.com/coreos/layering-examples/issues/49
=> replace-systemd: workaround for systemctl wrap issue

kernel-rt/Containerfile
It's about time that we have an example that demonstrates how to replace the (throughput-oriented) `kernel` with `kernel-rt` and test it in CI.
=> kernel-rt: New example

inject-go-binary/Containerfile
A big deal about the move to custom containers is that user content is treated the same way as OS content.  We should encourage storing *custom* systemd units in `/usr` so that they also end up underneath the read-only bind mount too.
While we're here, also do the "static enablement" pattern to force the unit on, regardless of presets.  Because thinking about presets is just annoying and unnecessary really.  If I'm injecting my custom service, there's really *no* scenario where I want some other preset file to control its enablement.
=> inject-go-binary: Move service into `/usr`, statically enabled

build-zfs-module/Containerfile
`uname -p` is broken under F38 and returns "unknown". See https://bugzilla.redhat.com/show_bug.cgi?id=2121153.
=> fix(build-zfs): Replace `uname -p` in script

build-zfs-module/Containerfile
CoreOS stable is now fedora 38, updating the default BUILDER_VERSION ARG value.
=> build-zfs-module: Update builder to use f38

.github/workflows/initramfs-module.yml, README.md, initramfs-module/Containerfile
Demos generating a initramfs with specific modules added and omitted.
=> initramfs-module: add example adding a module to the initramfs

README.md, loading-kernel-module/Containerfile, loading-kernel-module/README.md, loading-kernel-module/fcos-config.fcc
This example will demo how a pre-compiled kernel-module can be loaded into the worker nodes of a cluster using the CoreOS Layering functionality.
---
As requested https://github.com/ybettan/coreos-layering-driver-toolkit/pull/4#issuecomment-1572518239.
This is indeed a good idea to have it here as well.
/cc @cgwalters
=> Adding the loading-kernel-module example.

build-zfs-module/Containerfile
1. The kernel module was not loaded and it required running `depmod` as well as writing into `/etc/modules-load.d`
2. Updated example to use FCOS 39 and added an example command that can be used to set BUILDER_VERSION to the latest
3. Do not install development/test packages for ZFS, significantly reducing image size
=> Fixed and updated ZFS example
